openapi: 3.0.0
info:
  title: Temperatura e humidade capturadas pelo sensor HT11
  description: API para acessar dados do sensor
  version: 1.0.0
servers:
  - url: http://apaixonautas.com.br/consulta.php
paths:
  /consulta:
    get:
      summary: Obtém os dados de temperatura e humidade
      description: Retorna uma lista de dados de temperatura e humidade ordenados por timestamp.
      responses:
        '200':
          description: Lista de dados de temperatura e humidade
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    temperature:
                      type: number
                      format: float
                      example: 23.45
                    timestamp:
                      type: string
                      format: date-time
                      example: "2023-06-12T15:30:00Z"
        '500':
          description: Erro interno no servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Erro ao conectar ao banco de dados ou ao carregar log no arquivo"
